services:
  api:
    build: ./backend
    container_name: sbdl_api
    expose:
      - "8000"

  nginx:
    image: owasp/modsecurity-crs:nginx
    container_name: sbdl_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      # WAF config mount
      - ./waf/modsecurity.conf:/etc/nginx/modsec/modsecurity.conf:ro
      - ./waf/crs-setup.conf:/etc/nginx/modsec/crs-setup.conf:ro
    depends_on:
      - api
